backend:
  name: git-gateway
  branch: main # change this to your main branch name if different
media_folder: "public/images/posts" # Media files will be stored in the repo under public/images
public_folder: "/images/posts" # The src attribute for uploaded media will begin with /images
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    extension: "mdx"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Game Title", name: "gameTitle", widget: "string", required: false }
      - name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "url", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
          - { label: "Filename", name: "filename", widget: "string", required: false, pattern: ['^[^\\s]*$', 'Filename should not contain spaces'] }
      - { label: "Body", name: "body", widget: "markdown" }